### ISSUE TITLE
Some thoughts on encoding section

### ISSUE THREAD

**Issue by zerkms** [JakobKallin/Excess-XSS#4]
It states that:

> there are several built-in methods and properties that automatically encode all data in a context-aware manner:

and uses

``` js
element.setAttribute(attribute, userInput)
```

as an example.

While that is not true: encoding is necessary to prevent AST transformation of an HTML, that is a kind of seriailsed DOM.

Due to that DOM itself is not affected to the XSS, so it may accept anything and should not do any extra encoding, since what you're passing is already treated as a parameter value and cannot mutate the tree.

Thoughts?

**Comment by JakobKallin** [comment]
You are right about the DOM methods not technically having anything to do with encoding. The reason that passage is in there is because many developers are mainly familiar with `innerHTML`, which is technically part of the DOM but still requires us to worry about encoding. In other words, it's mostly there as a contrast. In a perfect world with no `innerHTML`, where we could let strings be strings and trees be trees, we probably wouldn't need to mention it.

**Comment by JakobKallin** [comment]
You are right about the DOM methods not technically having anything to do with encoding. The reason that passage is in there is because many developers are mainly familiar with `innerHTML`, which is technically part of the DOM but still requires us to worry about encoding. In other words, it's mostly there as a contrast. In a perfect world with no `innerHTML`, where we could let strings be strings and trees be trees, we probably wouldn't need to mention it.

**Comment by zerkms** [comment]
Yep, I see your point: it's not that a "problem" in fact, indeed.

How about closing this then?

**Comment by JakobKallin** [comment]
No problem. Thanks for your feedback!

**Comment by JakobKallin** [comment]
No problem. Thanks for your feedback!
